# Generated by Django 5.2.8 on 2025-11-19 15:44

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articleembedding'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='articleembedding',
            index=pgvector.django.indexes.HnswIndex(ef_construction=256, fields=['embedding'], m=16, name='article_embedding_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
